### ISSUE TITLE
On Windows Mixed Reality, VRServer.exe crashes

### ISSUE THREAD

**Issue by AThingWithAThing** [matzman666/OpenVR-InputEmulator#64]
Using the Lenovo Explorer here. So, whenever selecting stuff on the dashboard, VRServer.exe is closed and SteamVR is exited. This is on the latest version of the InputEmulator, 1.3, on the stable branch.

**Comment by boynet** [comment]
+1

**Comment by AThingWithAThing** [comment]
Just double checked the issue. I have no issues with the temporary beta branch so far.

**Comment by matzman666** [comment]
It outright crashes? Windows Mixed Reality devices are currently not fully supported due to me not owning one, but at least they shouldn't crash vrserver.exe.

> it keeps crashing even after uninstalling.

Which is even more strange. The uninstaller removes all files, the only thing I don't roll back during uninstallation is setting *activateMultipleDrivers*  to *true* in the steamvr.vrsettings file. Maybe the new SteamVR does not like it when other drivers are loaded alongside the WMR driver. You could try to delete this setting.

Either way, could you send me your log files after running (and crashing) it with the new SteamVR version to help me with getting the WMR devices fully supported? You can find the log file in *[SteamVR-InstallationFolder]\drivers\00vrinputemulator\bin\win64*.

**Comment by AThingWithAThing** [comment]
Here's my log file in the stable branch.
[driver_vrinputemulator.log](https://github.com/matzman666/OpenVR-InputEmulator/files/1636547/driver_vrinputemulator.log)

**Comment by drowhunter** [comment]
i can confirm the same thing is happening with the samsung odyssey.  i switched back to the input emulator branch and its working again

**Comment by matzman666** [comment]
> Here's my log file in the stable branch.

Is this really the current stable branch? According to that log file the WMR driver does not use the new driver API at all, which makes these crashes very mysterious.

When you uninstall Input Emulator does it still crash?

**Comment by CharlieQLe** [comment]
@matzman666 
I'm sure it's the stable branch. Here is another log file though: [driver_vrinputemulator.log](https://github.com/matzman666/OpenVR-InputEmulator/files/1661535/driver_vrinputemulator.log)

It also crashes after being uninstalled because when VRServer crashes, any dashboard application like the Input Emulator or Advanced Settings is still open, causing the files to not actually be uninstalled when the uninstaller is run without closing the program in task manager.

**Comment by matzman666** [comment]
Ok, then the WMR driver really does still use the old API. 

Did you try to uninstall it while SteamVR was still running? This is not a supported use case and there will be left-over files. You need to close SteamVR before uninstalling.

**Comment by CharlieQLe** [comment]
@matzman666 I did not uninstall it while SteamVR was running- the dashboard was still running though and the icon for SteamVR in the top right corner of Steam was green. The only fix is to use task manager to close out the dashboard programs and restart Steam. I don't know if restarting Steam ends the programs though. It's a small issue not related to this though I believe.

**Comment by CharlieQLe** [comment]
@matzman666 The new Windows Mixed Reality for SteamVR driver update fixes this by using the new input system!
